version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:2.1.0
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
      - "8080:8080"
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=8080
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/run/user/1000/docker.sock:/var/run/docker.sock"

  consumer:
    image: lambda_logs
    build: ./lambda_logs
    tty: true
    environment:
      AWS_ENDPOINT_URL: http://localstack:4566
      AWS_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
      AWS_LAMBDA_NAME: consumer
      AWS_ACCESS_KEY_ID: some
      AWS_SECRET_ACCESS_KEY: thing

  producer:
    image: lambda_logs
    build: ./lambda_logs
    tty: true
    environment:
      AWS_ENDPOINT_URL: http://localstack:4566
      AWS_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
      AWS_LAMBDA_NAME: producer
      AWS_ACCESS_KEY_ID: some
      AWS_SECRET_ACCESS_KEY: thing

  logs:
      image: amir20/dozzle:latest
      ports:
      - 8888:8080
      volumes:
      - /run/user/1000/docker.sock:/var/run/docker.sock:ro
